require("user.impatient")
require("user.neovide")
require("user.packer-plugins")
require("user.options")
require("user.keymaps")
require("user.autocommands")
require("user.colorscheme")
require("user.completion")
require("user.telescope")
-- require("user.illuminate")
require("user.lsp.mason")
require("user.lsp.lspsaga")
require("user.lsp.lspconfig")
require("user.lsp.null-ls")
require("user.treesitter")
require("user.highlights")
